language: ruby
rvm:
  - 2.3.3

install:
  - bundle install

script:
  - jekyll build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  fqdn: docs.terminal.ink
  on:
    branch: master

branches:
  only:
    - master

exclude:
  - vendor

sudo: false
