language: ruby
rvm:
  - 2.3.4

install:
  - bundle install

script:
  - jekyll build

deploy:
  local-dir: docs
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  fqdn: docs.terminal.ink
  skip_cleanup: true
  edge:
    branch: v1.8.47
  on:
    branch: master

branches:
  only:
    - master

exclude:
  - vendor

sudo: false
