title: Terminal.ink Documentation
description: Documentation for Terminal.ink

domain: "https://docs.terminal.ink"
baseurl: ""
url: "https://docs.terminal.ink"

destination: docs

encoding: utf-8

# include: ['_pages', '_docs']

markdown: kramdown

kramdown:
  auto_ids: true

sass:
  sass_dir: _sass
  style: compressed

collections_dir: _collections
collections:
  meta:
    output: true
  ls:
    output: true
  index:
    output: true
    permalink: /:name
  cats:
    output: true
  api:
    output: true
  "7517":
    output: true
  blog:
    output: true
  linus:
    output: true
